[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Store premium card dollars to global variable before evaluate play and reset after play
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.FUNCS.evaluate_play = function(e)"
position = "after"
match_indent = true
payload = """
G.bplus_premium_card_dollars = bplus_calculate_premium_card_dollars()
"""
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.modifiers.debuff_played_cards then"
position = "before"
match_indent = true
payload = """
G.bplus_premium_card_dollars = nil
"""

# Add method for modify playing card effect
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local jokers = card:calculate_joker(context)"
position = "before"
match_indent = true
payload = """
if card.ability.set == "Enhanced" and type(card.config.center.modify_effect) == "function" then
  card.config.center:modify_effect(card, context, ret.playing_card)
end

"""
