[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Add option param for create_card and get_current_pool function
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "function create_card(_type, area, legendary, _rarity, skip_materialize, soulable, forced_key, key_append)"
position = "at"
match_indent = true
payload = """
function create_card(_type, area, legendary, _rarity, skip_materialize, soulable, forced_key, key_append, opt)
  opt = opt or {}
"""

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local _pool, _pool_key = get_current_pool(_type, _rarity, legendary, key_append)"
position = "at"
match_indent = true
payload = """
local _pool, _pool_key = get_current_pool(_type, _rarity, legendary, key_append, { forced_rarity = opt.forced_rarity })
"""

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "function get_current_pool(_type, _rarity, _legendary, _append)"
position = "at"
match_indent = true
payload = """
function get_current_pool(_type, _rarity, _legendary, _append, opt)
  opt = opt or {}
"""

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "rarity = (_legendary and 4) or (rarity > 0.95 and 3) or (rarity > 0.7 and 2) or 1"
position = "after"
match_indent = true
payload = """
if opt.forced_rarity then
  rarity = opt.forced_rarity
end
"""

# Add some colors to loc_colour function
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.ARGS.LOC_COLOURS = G.ARGS.LOC_COLOURS or {"
position = "after"
match_indent = true
payload = """
eternal = G.C.ETERNAL,
"""

