[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Add Tag trigger context
[[patches]]
[patches.regex]
target = "functions/state_events.lua"
pattern = '''(?<indent>[ \t])*for i = 1, #G\.jokers\.cards do
[ \t]*G\.jokers\.cards\[i\]:calculate_joker\(\{setting_blind = true, blind = G\.GAME\.round_resets\.blind\}\)
[ \t]*end
'''
line_prepend = "$indent"
position = "after"
payload = """
for _, t in ipairs(G.GAME.tags) do
  t:apply_to_run { type = "setting_blind", blind = G.GAME.round_resets.blind }
end
"""
